"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

function Field({ label, value, update, step = 1, suffix }: { label: string; value: number; update: (value: number) => void; step?: number; suffix?: string }) {
  return <label>{label}{suffix && <small>{suffix}</small>}<input type="number" min="0" step={step} value={value} onChange={(e) => update(Math.max(0, Number(e.target.value)))} /></label>;
}

export default function CalculatorsPage() {
  const [miles, setMiles] = useState(12000); const [mpg, setMpg] = useState(28); const [gas, setGas] = useState(3.45); const [efficiency, setEfficiency] = useState(3.3); const [electricity, setElectricity] = useState(0.18);
  const [systemCost, setSystemCost] = useState(22000); const [incentive, setIncentive] = useState(30); const [annualSavings, setAnnualSavings] = useState(2100);
  const [currentBill, setCurrentBill] = useState(165); const [usageChange, setUsageChange] = useState(0); const [rateChange, setRateChange] = useState(5);
  const ev = useMemo(() => { const gasCost = miles / Math.max(mpg, .1) * gas; const evCost = miles / Math.max(efficiency, .1) * electricity; return { gasCost, evCost, difference: gasCost - evCost }; }, [miles, mpg, gas, efficiency, electricity]);
  const solar = useMemo(() => { const netCost = systemCost * (1 - incentive / 100); return { netCost, payback: annualSavings ? netCost / annualSavings : 0 }; }, [systemCost, incentive, annualSavings]);
  const bill = useMemo(() => currentBill * (1 + usageChange / 100) * (1 + rateChange / 100), [currentBill, usageChange, rateChange]);

  return <main className="article-page"><header className="article-header"><Link className="wordmark" href="/"><span>GREENER</span> NUMBERS</Link><Link href="/methodology">Methodology</Link></header><section className="calculator-page"><p className="eyebrow">Open tools</p><h1>Make the assumptions visible.</h1><p className="article-dek">These are quick, transparent estimates—not sales quotes or individualized financial advice. Change every assumption to fit your situation.</p>
    <div className="calculator-tool" id="ev"><div><p className="eyebrow">01 · Transportation</p><h2>EV vs. gas fuel cost</h2><p>Compares annual energy cost only. It does not include purchase price, insurance, maintenance, financing, incentives, or public-charging premiums.</p></div><div className="calculator full"><div className="inputs calculator-inputs"><Field label="Annual miles" value={miles} update={setMiles}/><Field label="Gas mpg" value={mpg} update={setMpg} step={0.1}/><Field label="Gas price" suffix="$/gal" value={gas} update={setGas} step={0.01}/><Field label="EV efficiency" suffix="mi/kWh" value={efficiency} update={setEfficiency} step={0.1}/><Field label="Electricity" suffix="$/kWh" value={electricity} update={setElectricity} step={0.01}/></div><div className="calc-results"><div><span>Gas car</span><b>${ev.gasCost.toLocaleString(undefined,{maximumFractionDigits:0})}</b></div><div><span>EV</span><b>${ev.evCost.toLocaleString(undefined,{maximumFractionDigits:0})}</b></div><div className={ev.difference >= 0 ? "savings" : "savings negative"}><span>{ev.difference >= 0 ? "EV fuel savings" : "EV fuel premium"}</span><b>${Math.abs(ev.difference).toLocaleString(undefined,{maximumFractionDigits:0})}<small>/year</small></b></div></div></div></div>
    <div className="calculator-tool" id="solar"><div><p className="eyebrow">02 · Home energy</p><h2>Solar payback</h2><p>A simple payback estimate based on your after-incentive system cost and expected first-year savings. Financing, production changes, utility rules, and maintenance can change the outcome.</p></div><div className="calculator full"><div className="inputs calculator-inputs three"><Field label="Installed cost" suffix="$" value={systemCost} update={setSystemCost}/><Field label="Incentive" suffix="%" value={incentive} update={setIncentive} step={1}/><Field label="Expected annual savings" suffix="$" value={annualSavings} update={setAnnualSavings}/></div><div className="calc-results"><div><span>After incentive cost</span><b>${solar.netCost.toLocaleString(undefined,{maximumFractionDigits:0})}</b></div><div><span>First-year savings</span><b>${annualSavings.toLocaleString(undefined,{maximumFractionDigits:0})}</b></div><div className="savings"><span>Simple payback</span><b>{solar.payback.toFixed(1)}<small> years</small></b></div></div></div></div>
    <div className="calculator-tool" id="bill"><div><p className="eyebrow">03 · Electricity</p><h2>Electricity bill change</h2><p>See how separate usage and rate changes combine. This uses your current monthly bill as a starting point and does not model fixed charges, taxes, or time-of-use pricing.</p></div><div className="calculator full"><div className="inputs calculator-inputs three"><Field label="Current monthly bill" suffix="$" value={currentBill} update={setCurrentBill}/><Field label="Usage change" suffix="%" value={usageChange} update={setUsageChange} step={1}/><Field label="Rate change" suffix="%" value={rateChange} update={setRateChange} step={1}/></div><div className="calc-results"><div><span>Current monthly bill</span><b>${currentBill.toLocaleString()}</b></div><div><span>Estimated new bill</span><b>${bill.toLocaleString(undefined,{maximumFractionDigits:0})}</b></div><div className="savings"><span>Monthly change</span><b>${Math.abs(bill-currentBill).toLocaleString(undefined,{maximumFractionDigits:0})}<small>{bill >= currentBill ? " more" : " less"}</small></b></div></div></div></div>
    <p className="method">For methodology and primary sources, visit <Link href="/methodology">our methodology</Link>. For full vehicle ownership comparisons, use the U.S. Department of Energy’s Alternative Fuels Data Center calculator.</p></section></main>;
}
