import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteFooter, SiteHeader } from "../../../../components/site-header";
import { Breadcrumbs, MethodologyBox, NewsletterCTA } from "../../../../components/platform";
import { pageMetadata } from "../../../../lib/site";

type Props={params:Promise<{slug:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;return pageMetadata({title:`${slug.split("-").map(x=>x[0]?.toUpperCase()+x.slice(1)).join(" ")} EV comparison | Greener Numbers`,description:"A future source-verified EV ownership cost comparison. Use current calculators until verified vehicle records are published.",path:`/ev/compare/${slug}`})}
export default async function Comparison({params}:Props){const {slug}=await params;if(!/^[a-z0-9-]+$/.test(slug))notFound();return <><SiteHeader/><main className="platform-main" id="main-content"><Breadcrumbs items={[{label:"Home",href:"/"},{label:"EV & Transportation",href:"/ev"},{label:"EV comparisons"}]}/><section className="tool-hero"><p className="eyebrow">EV comparison</p><h1>Vehicle comparison data is not published yet.</h1><p>Greener Numbers will publish comparison pages only after each vehicle specification, fuel assumption, electricity rate context, and incentive claim is source-verified and time-stamped.</p></section><MethodologyBox><p><strong>Why this is not a guessed comparison:</strong> battery capacity, usable capacity, EPA efficiency, range, connectors, charging speed, purchase price, local rates, fuel price, and incentives all need source-specific evidence. A page is not generated merely because a URL exists.</p></MethodologyBox><section className="related-content"><h2>Use current calculators</h2><Link href="/ev/ev-vs-gas-calculator">EV vs. Gas Calculator →</Link><Link href="/ev/charging-cost-calculator">EV Charging Cost Calculator →</Link></section><NewsletterCTA/></main><SiteFooter/></>}
