import type { Metadata } from "next";
import Link from "next/link";
import { DataMeta, EnergyNowFallback, GridDemandChart, MonthlyResidentialPrice, NewsletterCTA } from "../../components/platform";
import { SiteFooter, SiteHeader } from "../../components/site-header";
import { eiaSources, getEnergyNowData } from "../../lib/data/eia";
import { dataStatus, nationalElectricity, stateMetrics } from "../../lib/data/energy";

export const revalidate = 3600;
export const metadata: Metadata = { title: "Electricity prices and bills | Greener Numbers", description: "Understand residential electricity prices, household bills, state differences, and the inputs behind an electricity bill.", alternates: { canonical: "/electricity" } };

export default async function Electricity() {
  const energyNow = await getEnergyNowData();
  return <><SiteHeader /><main id="main-content" className="platform-main"><section className="page-hero"><p className="eyebrow">Electricity</p><h1>Understand what is driving your electricity cost.</h1><p>Explore rates, bills, state comparisons, and the difference between an average retail price and the tariff on your own utility bill.</p><div className="actions"><Link className="button primary" href="/tools/electricity-bill-calculator">Calculate your bill →</Link><Link className="button text" href="/electricity-prices/texas">Browse state pages</Link></div></section><section className="number-grid"><div><span>National residential rate</span><b>{nationalElectricity.rate}¢</b><small>per kWh · launch snapshot</small></div><div><span>Typical monthly bill</span><b>${nationalElectricity.bill}</b><small>national average · launch snapshot</small></div><div><span>Year-over-year change</span><b>+{nationalElectricity.change}%</b><small>launch snapshot</small></div></section>{energyNow ? <GridDemandChart demand={energyNow.demand} updatedAt={energyNow.demandUpdatedAt} source={eiaSources.grid} /> : <EnergyNowFallback />}{energyNow?.residentialPrice && <MonthlyResidentialPrice {...energyNow.residentialPrice} source={eiaSources.retail} />}<section className="state-preview"><div><p className="eyebrow">State comparison</p><h2>Electricity prices differ by state—and so do bills.</h2><p>Every state page shows a transparent data-status card. Verified launch metrics appear only where a source-backed figure is currently available.</p></div><div>{stateMetrics.filter(s => s.rate).map(s => <Link href={`/electricity-prices/${s.slug}`} key={s.slug}><span>{s.name}</span><b>{s.rate}¢/kWh</b><small>${s.bill}/month · {s.change}% YoY</small></Link>)}</div></section><DataMeta source={dataStatus.source} updated={dataStatus.updated}><p>Hourly grid demand and monthly residential prices use distinct EIA datasets and update schedules. A price average is not a real-time tariff or individual utility bill.</p></DataMeta><NewsletterCTA /></main><SiteFooter /></>;
}
