"use client";
import { useMemo, useState } from "react";

type Tool = "electricity-bill-calculator" | "appliance-energy-cost-calculator" | "led-savings-calculator" | "heat-pump-savings-calculator" | "ev-vs-gas-calculator" | "solar-savings-calculator" | "home-energy-savings-calculator" | "energy-inflation-calculator";
const money = (value: number) => value.toLocaleString(undefined, { style: "currency", currency: "USD", maximumFractionDigits: 0 });
const Field = ({ label, value, set, step = 1, hint }: { label: string; value: number; set: (v: number) => void; step?: number; hint?: string }) => <label className="calc-field">{label}{hint && <small>{hint}</small>}<input type="number" min="0" step={step} value={value} onChange={(event) => set(Math.max(0, Number(event.target.value)))} /></label>;

export function CalculatorClient({ tool }: { tool: Tool }) {
  const [a, setA] = useState(tool === "electricity-bill-calculator" ? 900 : tool === "appliance-energy-cost-calculator" ? 1500 : tool === "led-savings-calculator" ? 10 : tool === "heat-pump-savings-calculator" ? 1800 : tool === "ev-vs-gas-calculator" ? 12000 : tool === "solar-savings-calculator" ? 165 : tool === "home-energy-savings-calculator" ? 1800 : 140);
  const [b, setB] = useState(tool === "electricity-bill-calculator" ? .18 : tool === "appliance-energy-cost-calculator" ? 4 : tool === "led-savings-calculator" ? 60 : tool === "heat-pump-savings-calculator" ? 35 : tool === "ev-vs-gas-calculator" ? 28 : tool === "solar-savings-calculator" ? 22000 : tool === "home-energy-savings-calculator" ? 15 : 3.2);
  const [c, setC] = useState(tool === "electricity-bill-calculator" ? 30 : tool === "appliance-energy-cost-calculator" ? 30 : tool === "led-savings-calculator" ? 9 : tool === "heat-pump-savings-calculator" ? 350 : tool === "ev-vs-gas-calculator" ? 3.45 : tool === "solar-savings-calculator" ? 8000 : tool === "home-energy-savings-calculator" ? 250 : 5);
  const [d, setD] = useState(tool === "electricity-bill-calculator" ? 0 : tool === "appliance-energy-cost-calculator" ? .18 : tool === "led-savings-calculator" ? 3 : tool === "heat-pump-savings-calculator" ? 10000 : tool === "ev-vs-gas-calculator" ? 3.3 : tool === "solar-savings-calculator" ? .18 : tool === "home-energy-savings-calculator" ? 0 : 10);
  const [e, setE] = useState(tool === "led-savings-calculator" ? .18 : tool === "heat-pump-savings-calculator" ? 2000 : 0);
  const result = useMemo(() => {
    if (tool === "electricity-bill-calculator") { const period = a * b; return { primary: money(period), label: "Estimated bill for this period", rows: [["Estimated yearly electricity cost", money(period * 365 / Math.max(c, 1))], ["Cost per day", money(period / Math.max(c, 1))], ["Energy used", `${a.toLocaleString()} kWh`]] }; }
    if (tool === "appliance-energy-cost-calculator") { const kwhDay = a / 1000 * b; const month = kwhDay * c * d; return { primary: money(month), label: "Estimated monthly operating cost", rows: [["Energy use", `${(kwhDay * c).toFixed(1)} kWh/month`], ["Cost per day", money(kwhDay * d)], ["Cost per year", money(month * 12)]] }; }
    if (tool === "led-savings-calculator") { const hoursYear = d * 365; const oldCost = a * b / 1000 * hoursYear * e; const ledCost = a * c / 1000 * hoursYear * e; const savings = oldCost - ledCost; return { primary: money(savings), label: "Estimated electricity savings per year", rows: [["Old bulbs annual cost", money(oldCost)], ["LED bulbs annual cost", money(ledCost)], ["Energy avoided", `${((a * (b - c) / 1000) * hoursYear).toFixed(0)} kWh/year`], ["Monthly savings", money(savings / 12)]] }; }
    if (tool === "heat-pump-savings-calculator") { const avoidedFuelCost = a * b / 100; const annualNetSavings = avoidedFuelCost - c; const netProjectCost = Math.max(0, d - e); return { primary: money(annualNetSavings), label: annualNetSavings >= 0 ? "Estimated annual net energy savings" : "Estimated annual net energy-cost increase", rows: [["Avoided heating-fuel cost", money(avoidedFuelCost)], ["Added annual electricity cost", money(c)], ["Net installed cost", money(netProjectCost)], ["Simple payback", annualNetSavings > 0 ? `${(netProjectCost / annualNetSavings).toFixed(1)} years` : "Not available"]] }; }
    if (tool === "ev-vs-gas-calculator") { const gasCost = a / Math.max(b, .1) * c; const evCost = a / Math.max(d, .1) * .18; const diff = gasCost - evCost; return { primary: money(Math.abs(diff)), label: diff >= 0 ? "Estimated EV fuel savings per year" : "Estimated EV fuel premium per year", rows: [["Gas vehicle annual fuel cost", money(gasCost)], ["EV annual electricity cost", money(evCost)], ["Monthly difference", money(Math.abs(diff) / 12)], ["Gas cost per mile", money(gasCost / Math.max(a, 1))]] }; }
    if (tool === "solar-savings-calculator") { const annual = Math.min(a * 12, c * d); const net = b * .7; const payback = net / Math.max(annual, 1); return { primary: `${payback.toFixed(1)} years`, label: "Approximate simple payback", rows: [["Estimated annual bill savings", money(annual)], ["After-incentive system cost", money(net)], ["10-year estimated savings", money(annual * 10 - net)], ["20-year estimated savings", money(annual * 20 - net)]] }; }
    if (tool === "home-energy-savings-calculator") { const annual = a * b / 100; const net = annual - c; return { primary: money(Math.max(net, 0)), label: "Estimated first-year net savings", rows: [["Estimated annual bill savings", money(annual)], ["One-time upgrade cost", money(c)], ["Simple payback", annual ? `${(c / annual).toFixed(1)} years` : "—"], ["Assumption", "Editable national-screening estimate"]] }; }
    const future = a * Math.pow(1 + b / 100, c); return { primary: money(future - a), label: `Estimated increase over ${c} years`, rows: [["Current annual energy cost", money(a)], ["Assumed annual change", `${b}%`], ["Future annual cost", money(future)], ["Time period", `${c} years`]] };
  }, [a, b, c, d, e, tool]);
  const fields = tool === "electricity-bill-calculator" ? [["Electricity usage", a, setA, 1, "kWh"], ["Electricity rate", b, setB, .01, "$/kWh"], ["Billing period", c, setC, 1, "days"]] : tool === "appliance-energy-cost-calculator" ? [["Appliance wattage", a, setA, 1, "watts"], ["Hours used per day", b, setB, .1, "hours"], ["Days used per month", c, setC, 1, "days"], ["Electricity rate", d, setD, .01, "$/kWh"]] : tool === "led-savings-calculator" ? [["Number of bulbs", a, setA, 1, "bulbs"], ["Old bulb wattage", b, setB, 1, "watts"], ["LED bulb wattage", c, setC, 1, "watts"], ["Hours used per day", d, setD, .1, "hours"], ["Electricity rate", e, setE, .01, "$/kWh"]] : tool === "heat-pump-savings-calculator" ? [["Current annual heating-fuel cost", a, setA, 50, "$"], ["Expected heating-fuel reduction", b, setB, 1, "%"], ["Added annual electricity cost", c, setC, 25, "$"], ["Installed project cost", d, setD, 100, "$"], ["Entered incentives", e, setE, 50, "$"]] : tool === "ev-vs-gas-calculator" ? [["Annual miles driven", a, setA, 1, "miles"], ["Gas vehicle efficiency", b, setB, .1, "MPG"], ["Gasoline price", c, setC, .01, "$/gallon"], ["EV efficiency", d, setD, .1, "mi/kWh"]] : tool === "solar-savings-calculator" ? [["Current monthly electric bill", a, setA, 1, "$"], ["Solar system cost", b, setB, 100, "$"], ["Estimated annual generation", c, setC, 100, "kWh"], ["Electricity rate", d, setD, .01, "$/kWh"]] : tool === "home-energy-savings-calculator" ? [["Current yearly energy spend", a, setA, 50, "$"], ["Expected bill reduction", b, setB, 1, "%"], ["Upgrade cost", c, setC, 50, "$"]] : [["Current annual energy cost", a, setA, 10, "$"], ["Annual energy inflation", b, setB, .1, "%"], ["Years", c, setC, 1, "years"]];
  return <section className="calculator-panel"><div className="calculator-fields">{fields.map(([label, value, setter, step, hint]) => <Field key={String(label)} label={String(label)} value={value as number} set={setter as (value: number) => void} step={step as number} hint={String(hint)} />)}</div><output className="calculator-output"><span>{result.label}</span><strong>{result.primary}</strong><div>{result.rows.map(([label, value]) => <p key={label}><span>{label}</span><b>{value}</b></p>)}</div></output></section>;
}
