"use client";
import Link from "next/link";
import { useMemo, useRef, useState } from "react";
import { trackEvent } from "../lib/analytics";
import { calculateChargingCost, calculateEvVsGas, calculateHomeCharger, DEFAULT_CHARGING_EFFICIENCY } from "../lib/ev/calculations";
import { evVehicles } from "../lib/ev/vehicles";

type Kind = "charging" | "comparison" | "home";
const dollars = (value: number, digits = 0) => value.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: digits, minimumFractionDigits: digits });
const number = (value: number) => Number.isFinite(value) ? value : 0;
function Input({ label, value, onChange, step = 1, hint }: { label: string; value: number; onChange: (value: number) => void; step?: number; hint?: string }) { return <label className="calc-field">{label}{hint && <small>{hint}</small>}<input type="number" min="0" step={step} value={value} onChange={(event) => onChange(Math.max(0, number(Number(event.target.value))))} /></label>; }
function useUrlState(defaults: Record<string, number>) { const [values, setValues] = useState(() => { if (typeof window === "undefined") return defaults; const params = new URLSearchParams(window.location.search); return Object.fromEntries(Object.entries(defaults).map(([key, value]) => [key, params.has(key) ? number(Number(params.get(key))) : value])); }); const change = (key: string, value: number) => { const next = { ...values, [key]: value }; setValues(next); const params = new URLSearchParams(); Object.entries(next).forEach(([name, item]) => params.set(name, String(item))); window.history.replaceState(null, "", `${window.location.pathname}?${params}`); }; return [values, change] as const; }

export function EvCalculator({ kind, defaultRate }: { kind: Kind; defaultRate: number }) {
  const defaults: Record<string, number> = kind === "home" ? { charger: 550, labor: 650, electrical: 250, permit: 100, panel: 0, wiring: 250, other: 0, federal: 0, state: 0, utility: 0, manufacturer: 0, otherRebate: 0, miles: 12000, gas: 3.4, mpg: 28, rate: defaultRate, efficiency: 30 } : { miles: 12000, rate: defaultRate, efficiency: 30, battery: 75, home: 80, public: 20, publicRate: .45, mpg: 28, gas: 3.4 };
  const [v, set] = useUrlState(defaults); const started = useRef(false);
  const markStarted = () => { if (!started.current) { started.current = true; trackEvent("ev_calculator_started", { calculator: kind }); } };
  const charging = useMemo(() => calculateChargingCost({ milesPerYear: v.miles, efficiencyKwhPer100Miles: v.efficiency, batteryKwh: v.battery, electricityRate: v.rate / 100, homeChargingPercent: v.home, publicChargingPercent: v.public, publicChargingRate: v.publicRate, chargingEfficiency: DEFAULT_CHARGING_EFFICIENCY }), [v]);
  const comparison = useMemo(() => calculateEvVsGas({ milesPerYear: v.miles, efficiencyKwhPer100Miles: v.efficiency, electricityRate: v.rate / 100, homeChargingPercent: v.home, publicChargingPercent: v.public, publicChargingRate: v.publicRate, mpg: v.mpg, gasPrice: v.gas }), [v]);
  const homeCharging = useMemo(() => calculateChargingCost({ milesPerYear: v.miles, efficiencyKwhPer100Miles: v.efficiency, electricityRate: v.rate / 100, homeChargingPercent: 100, publicChargingPercent: 0, publicChargingRate: v.rate / 100 }), [v]);
  const home = useMemo(() => calculateHomeCharger({ chargerPrice: v.charger, laborCost: v.labor, electricalWork: v.electrical, permitCost: v.permit, panelUpgrade: v.panel, wiringCost: v.wiring, otherCost: v.other, federalIncentive: v.federal, stateIncentive: v.state, utilityRebate: v.utility, manufacturerRebate: v.manufacturer, otherRebate: v.otherRebate, annualSavings: Math.max(0, v.miles / Math.max(v.mpg, .1) * v.gas - homeCharging.annualCost) }), [v, homeCharging.annualCost]);
  const selectVehicle = (id: string) => { const vehicle = evVehicles.find((item) => item.id === id); if (!vehicle) return; set("battery", vehicle.batteryKwh); set("efficiency", vehicle.efficiencyKwhPer100Miles); trackEvent("ev_vehicle_selected", { vehicle: id }); };
  const complete = () => trackEvent(kind === "comparison" ? "ev_vs_gas_completed" : kind === "home" ? "home_charger_calculation_completed" : "ev_calculator_completed");
  const common = <><label className="calc-field">Choose an EV <small>Optional starter dataset</small><select defaultValue="" onChange={(event) => selectVehicle(event.target.value)}><option value="">Enter vehicle details manually</option>{evVehicles.map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.label}</option>)}</select></label><Input label="Annual miles driven" value={v.miles} onChange={(x) => set("miles", x)} hint="miles/year"/><Input label="EV efficiency" value={v.efficiency} onChange={(x) => set("efficiency", x)} step={.1} hint="kWh per 100 miles"/><Input label="Residential electricity rate" value={v.rate} onChange={(x) => set("rate", x)} step={.1} hint="¢/kWh — editable"/></>;
  if (kind === "home") return <section className="ev-calculator"><div className="calculator-fields" onFocus={markStarted}><Input label="Charger purchase price" value={v.charger} onChange={(x) => set("charger", x)} hint="$"/><Input label="Installation / labor" value={v.labor} onChange={(x) => set("labor", x)} hint="$"/><Input label="Electrical work" value={v.electrical} onChange={(x) => set("electrical", x)} hint="$"/><Input label="Permit cost" value={v.permit} onChange={(x) => set("permit", x)} hint="$"/><Input label="Panel upgrade" value={v.panel} onChange={(x) => set("panel", x)} hint="$"/><Input label="Wiring / circuit work" value={v.wiring} onChange={(x) => set("wiring", x)} hint="$"/><Input label="Other installation costs" value={v.other} onChange={(x) => set("other", x)} hint="$"/><Input label="Federal incentive" value={v.federal} onChange={(x) => set("federal", x)} hint="$"/><Input label="State incentive" value={v.state} onChange={(x) => set("state", x)} hint="$"/><Input label="Utility rebate" value={v.utility} onChange={(x) => set("utility", x)} hint="$"/><Input label="Manufacturer rebate" value={v.manufacturer} onChange={(x) => set("manufacturer", x)} hint="$"/><Input label="Other rebate" value={v.otherRebate} onChange={(x) => set("otherRebate", x)} hint="$"/>{common}<Input label="Gasoline price" value={v.gas} onChange={(x) => set("gas", x)} step={.01} hint="$/gallon"/><Input label="Comparison vehicle efficiency" value={v.mpg} onChange={(x) => set("mpg", x)} step={.1} hint="MPG"/></div><Result onComplete={complete} primary={dollars(home.netCost)} label="Estimated net installation cost" rows={[["Gross installation cost", dollars(home.grossCost)], ["Rebates and incentives", `−${dollars(home.rebates)}`], ["Estimated annual charging cost", dollars(homeCharging.annualCost)], ["Estimated gasoline cost avoided", dollars(v.miles / Math.max(v.mpg, .1) * v.gas)], ["Estimated annual fuel savings", dollars(home.annualSavings)], ["Simple payback", home.paybackYears === null ? "—" : `${home.paybackYears.toFixed(1)} years`]]} /></section>;
  const isComparison = kind === "comparison";
  return <section className="ev-calculator"><div className="calculator-fields" onFocus={markStarted}>{common}{!isComparison && <Input label="Battery capacity" value={v.battery} onChange={(x) => set("battery", x)} step={.1} hint="kWh"/>}<Input label="Home charging" value={v.home} onChange={(x) => set("home", x)} hint="% of charging"/><Input label="Public charging" value={v.public} onChange={(x) => set("public", x)} hint="% of charging"/><Input label="Public charging price" value={v.publicRate} onChange={(x) => set("publicRate", x)} step={.01} hint="$/kWh"/>{isComparison && <><Input label="Gas vehicle efficiency" value={v.mpg} onChange={(x) => set("mpg", x)} step={.1} hint="MPG"/><Input label="Gasoline price" value={v.gas} onChange={(x) => set("gas", x)} step={.01} hint="$/gallon"/></>}</div>{isComparison ? <Result onComplete={complete} primary={dollars(comparison.annualSavings)} label={comparison.annualSavings >= 0 ? "Estimated EV savings per year" : "Estimated EV premium per year"} rows={[["EV energy cost", `${dollars(comparison.monthlyCost)}/month`], ["Gasoline cost", `${dollars(comparison.gasMonthlyCost)}/month`], ["EV cost per mile", dollars(comparison.costPerMile, 3)], ["Gas cost per mile", dollars(comparison.gasCostPerMile, 3)], ["Monthly savings", dollars(comparison.monthlySavings)], ["Five-year energy / fuel savings", dollars(comparison.fiveYearSavings)]]} /> : <Result onComplete={complete} primary={dollars(charging.monthlyCost)} label="Estimated monthly charging cost" rows={[["Cost per full charge", dollars(charging.fullChargeCost)], ["Cost per 100 miles", dollars(charging.costPer100Miles)], ["Cost per mile", dollars(charging.costPerMile, 3)], ["Daily charging cost", dollars(charging.dailyCost)], ["Annual charging cost", dollars(charging.annualCost)], ["Estimated electricity used", `${Math.round(charging.energyKwh).toLocaleString()} kWh/year`], ["Home charging cost", dollars(charging.homeCost)], ["Public charging cost", dollars(charging.publicCost)]]} />}</section>;
}
function Result({ primary, label, rows, onComplete }: { primary: string; label: string; rows: string[][]; onComplete: () => void }) { return <output className="calculator-output ev-output"><span>{label}</span><strong>{primary}</strong><button className="button primary" type="button" onClick={onComplete}>Save this estimate</button><div>{rows.map(([label, value]) => <p key={label}><span>{label}</span><b>{value}</b></p>)}</div></output>; }

export function EvRelatedTools() { return <nav className="related-content" aria-label="Related EV tools"><h2>Keep planning</h2><Link href="/ev/charging-cost-calculator">EV Charging Cost Calculator →</Link><Link href="/ev/ev-vs-gas-calculator">Compare EV vs. Gas →</Link><Link href="/ev/home-charger-cost">Home Charger Installation Cost →</Link></nav>; }
