import { Suspense } from "react";
import type { Metadata } from "next";
import Link from "next/link";
import { EvCalculator } from "./ev-calculator";
import { Breadcrumbs, DataMeta, MethodologyBox, NewsletterCTA } from "./platform";
import { SiteFooter, SiteHeader } from "./site-header";
import { getUsResidentialRateDefault } from "../lib/data/eia";

const tools = [
  ["EV Charging Cost Calculator", "Estimate home, public, and blended charging costs from your driving and electricity assumptions.", "/ev/charging-cost-calculator"],
  ["EV vs. Gas Calculator", "Compare energy cost per mile, monthly spend, and five-year fuel savings.", "/ev/ev-vs-gas-calculator"],
  ["Home Charger Installation Calculator", "Estimate installation cost, incentives, fuel savings, and simple payback.", "/ev/home-charger-cost"],
  ["Cheapest Times to Charge", "Estimate potential savings from shifting charging to your own off-peak rate.", "/ev/cheapest-time-to-charge"],
  ["EV Charger Finder", "Search DOE/NREL public station data once the verified feed is connected.", "/ev/charger-finder"],
  ["EV rebates & incentives", "Track source-linked federal, state, local, and utility programs as verified records.", "/ev/incentives"],
] as const;

export const metadata: Metadata = { title: "EV & Transportation | Greener Numbers", description: "Calculate EV charging costs, compare electric and gasoline fuel costs, and estimate the economics of a home charger.", alternates: { canonical: "/ev" }, openGraph: { title: "The Real Cost of Going Electric | Greener Numbers", description: "Practical EV charging and ownership economics for household budgets.", url: "/ev" } };

export default function EvHub() { return <><SiteHeader /><main id="main-content" className="platform-main"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "EV & Transportation" }]} /><section className="page-hero"><p className="eyebrow">EV & Transportation</p><h1>The real cost of going electric.</h1><p>Calculate charging costs, compare EVs with gasoline vehicles, and see what a home charger could mean for your household budget. Estimates keep electricity, public charging, fuel, and installation assumptions visible.</p><div className="actions"><Link className="button primary" href="/ev/charging-cost-calculator">Calculate charging cost →</Link><Link className="button text" href="/ev/ev-vs-gas-calculator">Compare EV vs. gas →</Link></div></section><section className="platform-section"><div className="section-intro"><div><p className="eyebrow">Start with your costs</p><h2>Three practical calculators.</h2></div></div><div className="tool-cards">{tools.map(([title, description, href]) => <Link href={href} className="tool-card" key={href}><span>EV economics</span><h3>{title}</h3><p>{description}</p><b>Calculate →</b></Link>)}</div></section><section className="content-sections"><section><h2>Charging cost</h2><p>Separate home and public charging, account for charging losses, and override every energy-price input.</p></section><section><h2>Location and incentives</h2><p>Station discovery, rebates, and utility-rate research are being built around authoritative public sources—not dealer marketing or generic automotive news.</p></section><section><h2>What estimates exclude</h2><p>Purchase price, finance charges, insurance, maintenance, taxes, resale value, local tariffs, and real-time charger availability require separate analysis.</p></section></section><NewsletterCTA /></main><SiteFooter /></>;
}

async function CalculatorPage({ mode, title, description, formula, related }: { mode: "charging" | "compare" | "home"; title: string; description: string; formula: string; related: string }) { const rateDefault = mode === "home" ? null : await getUsResidentialRateDefault(); const schema = { "@context": "https://schema.org", "@type": "WebApplication", name: title, applicationCategory: "FinanceApplication", operatingSystem: "Web", description, offers: { "@type": "Offer", price: "0", priceCurrency: "USD" } }; return <><SiteHeader /><main id="main-content" className="platform-main"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "EV & Transportation", href: "/ev" }, { label: title }]} /><section className="tool-hero"><p className="eyebrow">EV economics tool</p><h1>{title}</h1><p>{description}</p><p className="tool-disclaimer">Results are estimates, not quotes or guaranteed savings. Actual cost depends on your vehicle, utility, charging network, taxes, driving, equipment, installation conditions, and available programs.</p></section><Suspense fallback={<div className="ev-calculator" aria-busy="true">Loading calculator…</div>}><EvCalculator mode={mode} rateDefault={rateDefault?.centsPerKwh} /></Suspense><MethodologyBox><p><strong>How we calculate this:</strong> {formula}</p><p>Electricity inputs are editable. When an official EIA price is available, use it as a starting point—not as your utility’s real-time tariff. Charging losses are an adjustable estimate. Public-charging pricing can vary by network, location, time, tax, and membership.</p></MethodologyBox><DataMeta source={mode === "home" ? "User-entered project costs and incentives" : "User-entered assumptions; U.S. Energy Information Administration starting rate when available"} updated="Calculator formulas reviewed August 2026"><p>Last updated reflects the formula review. Any EIA default remains editable and is not a local utility tariff. Inputs are not stored.</p></DataMeta><section className="related-content"><h2>Related EV tools</h2><Link href={related}>{related === "/ev/charging-cost-calculator" ? "EV Charging Cost Calculator" : related === "/ev/ev-vs-gas-calculator" ? "EV vs. Gas Calculator" : "Home Charger Cost Calculator"} →</Link><Link href="/ev">EV & Transportation hub →</Link></section><NewsletterCTA /></main><SiteFooter /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /></>; }

export function ChargingCalculatorPage() { return <CalculatorPage mode="charging" title="EV Charging Cost Calculator" description="Estimate what it costs to charge an EV at home, in public, or with a mix of both." formula="Energy used equals annual miles × kWh per 100 miles ÷ 100, then multiplied by the charging-loss factor. Charging cost equals delivered energy × the selected home or public electricity price." related="/ev/ev-vs-gas-calculator" />; }
export function CompareCalculatorPage() { return <CalculatorPage mode="compare" title="EV vs. Gas Calculator" description="Compare EV charging costs with gasoline spending using your mileage, efficiency, electricity, public-charging, and fuel-price assumptions." formula="EV cost uses the charging-cost calculation. Gasoline cost equals annual miles ÷ MPG × price per gallon. Savings are gasoline cost minus EV energy cost; five-year savings hold entered prices and driving constant." related="/ev/charging-cost-calculator" />; }
export function HomeChargerCalculatorPage() { return <CalculatorPage mode="home" title="Home EV Charger Installation Cost Calculator" description="Estimate the net cost of installing a home EV charger, potential fuel savings, and simple payback." formula="Gross installation cost is charger, labor, electrical work, permit, panel upgrade, and other costs. Net cost is gross cost minus entered incentives. Simple payback equals net installation cost ÷ estimated annual fuel savings." related="/ev/ev-vs-gas-calculator" />; }
