import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { CalculatorClient } from "../../../components/calculator-client";
import { Breadcrumbs, DataMeta, MethodologyBox, NewsletterCTA } from "../../../components/platform";
import { SiteFooter, SiteHeader } from "../../../components/site-header";
import { tools } from "../../../lib/tools";
import { pageMetadata } from "../../../lib/site";

export function generateStaticParams() { return tools.map(({slug}) => ({slug})); }
export function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{return params.then(({slug})=>{const tool=tools.find((item)=>item.slug===slug);return tool?pageMetadata({title:`${tool.title} | Greener Numbers`,description:tool.description,path:`/tools/${tool.slug}`}):{}});}
export default async function ToolPage({params}:{params:Promise<{slug:string}>}) { const {slug}=await params; const tool=tools.find((item)=>item.slug===slug); if(!tool) notFound(); const related=tools.filter((item)=>item.slug!==tool.slug).slice(0,3); const schema={"@context":"https://schema.org","@type":"SoftwareApplication",name:tool.title,applicationCategory:"FinanceApplication",operatingSystem:"Web",description:tool.description,offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}}; return <><SiteHeader/><main id="main-content" className="platform-main"><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Tools",href:"/tools"},{label:tool.title}]}/><section className="tool-hero"><p className="eyebrow">{tool.category} tool</p><h1>{tool.title}</h1><p>{tool.description}</p><p className="tool-disclaimer">Results are estimates for education. Change the inputs to reflect your situation; do not treat this as a quote or a guaranteed savings outcome.</p></section><CalculatorClient tool={tool.slug}/><MethodologyBox><p>This tool uses the inputs shown above only. It makes no claim about future prices, utility tariffs, equipment performance, taxes, financing, or incentives unless you enter them directly.</p><p><strong>Formula:</strong> calculations combine user-entered usage or annual distance with a unit energy cost, then convert the result to the stated time period.</p></MethodologyBox><DataMeta source="User-entered values; EIA and DOE methodology context" updated="Calculator formulas reviewed August 2026"><Link href="/electricity">Explore electricity price data →</Link></DataMeta><section className="related-content"><h2>Keep exploring</h2>{related.map((item)=><Link key={item.slug} href={`/tools/${item.slug}`}>{item.title} →</Link>)}</section><NewsletterCTA/></main><SiteFooter/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></>; }
