import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs, DataMeta, MethodologyBox, NewsletterCTA } from "../../../components/platform";
import { SiteFooter, SiteHeader } from "../../../components/site-header";
import { dataStatus, nationalElectricity, stateMetrics } from "../../../lib/data/energy";
import { pageMetadata } from "../../../lib/site";
export function generateStaticParams(){return stateMetrics.map(({slug})=>({state:slug}));} export function generateMetadata({params}:{params:Promise<{state:string}>}):Promise<Metadata>{return params.then(({state})=>{const entry=stateMetrics.find(s=>s.slug===state);return entry?pageMetadata({title:`${entry.name} electricity prices | Greener Numbers`,description:`Explore electricity-price context, bill estimates, and data-status information for ${entry.name}.`,path:`/electricity-prices/${entry.slug}`}):{}})};
export default async function StatePage({params}:{params:Promise<{state:string}>}){const {state}=await params;const entry=stateMetrics.find(s=>s.slug===state);if(!entry)notFound();const has=entry.rate!==undefined;return <><SiteHeader/><main id="main-content" className="platform-main"><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Electricity",href:"/electricity"},{label:`${entry.name} electricity prices`}]}/><section className="page-hero"><p className="eyebrow">State electricity data</p><h1>{entry.name} electricity prices</h1><p>{has?`A source-backed launch snapshot for ${entry.name}. Compare it with the national context, then estimate your own bill with your utility rate and usage.`:`The state-page architecture is ready for ${entry.name}. A verified metric has not been connected yet, so this page intentionally does not display a placeholder price.`}</p><Link className="button primary" href="/tools/electricity-bill-calculator">Calculate your electricity bill →</Link></section>{has?<section className="number-grid"><div><span>Average residential rate</span><b>{entry.rate}¢</b><small>per kWh</small></div><div><span>Typical monthly bill</span><b>${entry.bill}</b><small>launch snapshot</small></div><div><span>Year-over-year change</span><b>+{entry.change}%</b><small>launch snapshot</small></div><div><span>National comparison</span><b>{(entry.rate!-nationalElectricity.rate).toFixed(1)}¢</b><small>above national rate</small></div></section>:<section className="pending-data"><h2>Verified state metric pending</h2><p>Greener Numbers will show a rate, estimated monthly cost, annual estimate, year-over-year change, historical series, source release date, and national comparison after a reviewed dataset is connected.</p></section>}<MethodologyBox title="How to use this state page"><p>Average retail price is a revenue-per-kilowatthour measure. It is not necessarily the tariff you pay. Your bill can include usage, fixed charges, taxes, rate design, and time-based pricing.</p></MethodologyBox><DataMeta source={dataStatus.source} updated={dataStatus.updated}><p>{dataStatus.note}</p></DataMeta><NewsletterCTA/></main><SiteFooter/></>;}
