import type { Metadata } from "next";
import { Suspense } from "react";
import Link from "next/link";
import { EvCalculator } from "../../../components/ev-calculator";
import { SiteFooter, SiteHeader } from "../../../components/site-header";
import { Breadcrumbs, MethodologyBox, NewsletterCTA } from "../../../components/platform";
import { pageMetadata } from "../../../lib/site";

export const metadata: Metadata = pageMetadata({ title: "Cheapest Times to Charge an EV | Greener Numbers", description: "Estimate potential EV charging savings from shifting more charging to your utility's off-peak rate.", path: "/ev/cheapest-time-to-charge" });
export default function CheapestTime() { return <><SiteHeader /><main className="platform-main" id="main-content"><Breadcrumbs items={[{label:"Home",href:"/"},{label:"EV & Transportation",href:"/ev"},{label:"Cheapest Times to Charge"}]} /><section className="tool-hero"><p className="eyebrow">EV electricity rates</p><h1>Cheapest times to charge an EV</h1><p>Estimate how much shifting charging from peak periods to off-peak hours could change your monthly and annual electricity cost.</p><p className="tool-disclaimer">This is an educational estimate. Rate windows, taxes, fixed charges, plan rules, demand charges, and eligibility vary by utility. Use your own tariff, not an assumed national schedule.</p></section><Suspense fallback={<div className="ev-calculator" aria-busy="true">Loading calculator…</div>}><EvCalculator mode="offpeak" /></Suspense><MethodologyBox><p><strong>How we calculate this:</strong> annual charging energy equals miles × kWh per 100 miles ÷ 100 × the charging-loss factor. We compare that energy at your entered peak rate with the blend of your entered peak/off-peak rates and off-peak share.</p><p>Greener Numbers does not currently determine your utility’s plan or hours automatically. A utility-specific directory will be added only after verified tariff data is available.</p></MethodologyBox><section className="related-content"><h2>Related EV tools</h2><Link href="/ev/charging-cost-calculator">EV Charging Cost Calculator →</Link><Link href="/ev/incentives">EV rebates & incentives →</Link></section><NewsletterCTA /></main><SiteFooter /></> }
