import type { Metadata } from "next";
import Link from "next/link";
import { Breadcrumbs, MethodologyBox, NewsletterCTA } from "../../components/platform";
import { SiteFooter, SiteHeader } from "../../components/site-header";

export const metadata: Metadata = { title: "Energy incentives and rebates | Greener Numbers", description: "Find source-reviewed EV and home-charging incentives, and understand the data requirements for future solar and home-efficiency programs.", alternates: { canonical: "/incentives" } };

export default function IncentivesPage() { return <><SiteHeader /><main className="platform-main" id="main-content"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Incentives & rebates" }]} /><section className="page-hero"><p className="eyebrow">Incentives & rebates</p><h1>Incentives should be source-backed, not assumed.</h1><p>Search currently reviewed EV and home-charging records. Solar, battery, heat-pump, appliance, and utility programs will appear only after a source, location, eligibility, benefit, expiration, and verification date are recorded.</p><Link className="button primary" href="/ev/incentives">Search EV & charger incentives →</Link></section><section className="content-sections"><section><h2>What is available now</h2><p>Federal, state, local, and utility EV and charging-incentive records published through a server-side, source-reviewed database boundary.</p></section><section><h2>What a record includes</h2><p>Title, program type, geography, value text, eligibility, expiration/status, official source, source agency, and last-checked date.</p></section><section><h2>Before you decide</h2><p>Confirm eligibility with the administering agency or utility. A listed program is not a guarantee of a benefit or tax outcome.</p></section></section><MethodologyBox title="Publication standard"><p>No incentive is published from a generic summary or marketing page. Greener Numbers retains the source URL and review date, and treats fact-specific federal programs as eligibility-dependent.</p></MethodologyBox><NewsletterCTA /></main><SiteFooter /></>;
}
